### ISSUE TITLE
Climb animation and down doesn't add hair or shirts

### ISSUE THREAD

**Issue by cedavis8** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#203]
Just trying to use your excellent tool to make some test game sprites for a thing I'm developing, but the hair and shirts and upper body armor don't actually generate for any animation below "climb". So idle, etc, also don't have any hair or shirts lol.

**Comment by cedavis8** [comment]
Realized this may just not be done lol

**Comment by jrconway3** [comment]
Yeah, everything below the "death" animation is new so its not done yet. This issue keeps getting asked and I understand why, but its a bit annoying.

Here's what I suggest: Whatever assets you see that you want over those frames, please create a card for it if it doesn't exist already. I'm gradually adding more cards as well based on what I'm prioritizing. However, I'm the only person working on this right now, and it takes a lot of work to get these assets out.


The reason most hairstyles aren't done yet is because of animations--for longer hairstyles, they really need SOME sort of animations on them for the run animation, and probably jump, too. The new combat animations _might_ be okay, but it depends. That said, I think once run and jump are done, usually combat can just reuse those frames easily enough with little issue.


Also, there is an animations filter: you can use this filter to see what things are already done. There ARE some clothing assets, but the default "Male" sprite doesn't have them yet. I should probably get those done soon-ish, but right now I'm working on body armor.
